import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { marked } from 'marked';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const CONTENT_DIR = join(ROOT, 'content');
const OUTPUT = join(ROOT, 'js', 'data.js');

// Section definitions: maps markdown files to sections
const SECTION_MAP = [
  {
    file: 'index.md',
    group: 'RINGKASAN',
    id: 'ringkasan',
    title: 'Evaluasi Kinerja Triwulan II 2026',
  },
  {
    file: 'ketentuan-kinerja.md',
    group: 'KETENTUAN KINERJA',
    sections: [
      { id: 'predikat', title: 'Lima Predikat Kinerja', headingLevel: 2 },
      { id: 'anomali', title: 'Anomali Distribusi TW1 2026', headingLevel: 2 },
      { id: 'komposisi', title: 'Komposisi Distribusi Predikat', headingLevel: 2 },
    ],
  },
  {
    file: 'proses-evaluasi.md',
    group: 'PROSES EVALUASI',
    sections: [
      { id: 'tahapan', title: 'Tahapan Evaluasi Kinerja', headingLevel: 2 },
      { id: 'konfirmasi', title: 'Konfirmasi & Keberatan Pegawai', headingLevel: 2 },
      { id: 'dialog-tukin', title: 'Dialog Kinerja & Tunjangan', headingLevel: 2 },
    ],
  },
  {
    file: 'panel-kalibrasi.md',
    group: 'PANEL KALIBRASI',
    sections: [
      { id: 'panel-umum', title: 'Ketentuan Umum Panel Kalibrasi', headingLevel: 2 },
      { id: 'panel-peserta', title: 'Peserta & Tahapan Panel', headingLevel: 2 },
      { id: 'panel-fokus', title: 'Fokus Pembahasan Panel', headingLevel: 2 },
      { id: 'panel-korelasi', title: 'Korelasi Predikat & Nilai (K1/K2/K3)', headingLevel: 2 },
    ],
  },
  {
    file: 'referensi.md',
    group: 'REFERENSI',
    sections: [
      { id: 'contoh-surat', title: 'Contoh Surat Keterangan', headingLevel: 2 },
      { id: 'timeline', title: 'Garis Waktu Ringkas', headingLevel: 2 },
    ],
  },
];

function splitByH2(markdown) {
  // Split markdown by --- separator or ## headings
  const parts = markdown.split(/\n---\n/);
  return parts.map((p) => p.trim()).filter(Boolean);
}

function extractTitle(html, fallback) {
  // Try to extract title from <h1 class="title"> or ## heading
  const match = html.match(/<h1[^>]*>(.*?)<\/h1>/s);
  if (match) return match[1].replace(/<[^>]*>/g, '').trim();
  const h2 = html.match(/##\s+(.+)/);
  if (h2) return h2[1].trim();
  return fallback;
}

function buildSections() {
  const result = [];

  for (const def of SECTION_MAP) {
    const filePath = join(CONTENT_DIR, def.file);
    const raw = readFileSync(filePath, 'utf-8');

    if (def.sections) {
      // Multi-section file: split by ---
      const parts = splitByH2(raw);
      for (let i = 0; i < def.sections.length; i++) {
        const sec = def.sections[i];
        const md = parts[i] || '';
        const html = marked.parse(md);
        result.push({
          group: def.group,
          id: sec.id,
          title: sec.title,
          html: `\n${html.trim()}\n`,
        });
      }
    } else {
      // Single section file
      const html = marked.parse(raw);
      result.push({
        group: def.group,
        id: def.id,
        title: def.title,
        html: `\n${html.trim()}\n`,
      });
    }
  }

  return result;
}

const sections = buildSections();

// Use JSON then convert to single-quote JS for biome compatibility
const json = JSON.stringify(sections, null, 2);
const js = json
  .replace(/"([^"]+)":/g, '$1:')
  .replace(/"/g, "'")
  .replace(/\\'/g, "\\'");

const output = `// Auto-generated by scripts/build.js — DO NOT EDIT
// Run: npm run build
const sections = ${js};
`;

writeFileSync(OUTPUT, output, 'utf-8');
console.log(`✓ Built ${sections.length} sections → js/data.js`);
